apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
    replicas: 3  # Number of desired replicas
    selector:
        matchLabels:
        app: nginx
    template:
        metadata:
        labels:
            app: nginx
        spec:
        containers:
            - name: nginx
              image: nginx:latest  # Replace with your Docker image path
              ports:
                - containerPort: 80  # Replace with the port your Node.js app listens on